[project]
name = "test-automation-framework"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "flask>=2.2.3",
    "allure-pytest>=2.13.5",
    "python-jenkins==1.8.0",
    "jsonpath>=0.82.2",
    "pandas>=2.2.3",
    "pytest>=8.3.2",
    "pyyaml>=6.0.2",
    "requests>=2.32.3"
]